async function getSkillSet(req,res){
    const skillSet= [
          "House Cleaning", "Laundry", "Cooking", "Pet Care", "Babysitting", 
          "Childcare", "Elderly Care", "Home Care", "Gardening", "Landscaping", 
          "Outdoor Cleaning", "Patio Cleaning", "Driveway Cleaning", "Pool Cleaning", 
          "Snow Removal", "Fence Repair", "Painting", "Wall Repairs", "Furniture Assembly", 
          "Curtain Installation", "Blinds Installation", "Light Fixture Installation", 
          "Ceiling Fan Installation", "Outlet Installation", "TV Mounting", "Home Theater Setup", 
          "Home Office Setup", "Computer Troubleshooting", "Wi-Fi Setup", "Furniture Moving", 
          "Packing Services", "Unpacking Services", "Junk Removal", "Garage Organization", 
          "Closet Organization", "Pantry Organization", "Decluttering", "Carpet Cleaning", 
          "Upholstery Cleaning", "Mattress Cleaning", "Air Duct Cleaning", "Pest Control", 
          "Rodent Control", "Termite Control", "Bed Bug Treatment", "Ant Control", 
          "Mosquito Control", "Home Security Installation", "Alarm System Setup", 
          "Smart Lock Installation", "CCTV Installation", "Home Automation Setup", 
          "Home Appliance Repair", "Washing Machine Repair", "Refrigerator Repair", 
          "Microwave Repair", "Oven Repair", "Dishwasher Repair", "AC Repair", "Heater Repair", 
          "Plumbing", "Leaky Faucet Repair", "Toilet Installation", "Shower Installation", 
          "Sink Installation", "Water Heater Installation", "Roof Repair", "Chimney Repair", 
          "Siding Repair", "Window Repair", "Door Repair", "Sewer Line Repair", 
          "Custom Work", "Meal Preparation", "Food Delivery", "Pet Sitting", 
          "Dog Walking", "Cat Sitting", "Pet Grooming", "Fish Tank Cleaning", 
          "In-Home Nursing", "Lawn Mowing", "Tree Trimming", "Hedge Trimming", 
          "Weeding", "Plant Care", "Vegetable Gardening", "Fertilizing", 
          "Pressure Washing", "Leaf Raking", "Picture Hanging", "Home Security Monitoring", 
          "Roof Inspection", "Energy Efficiency Consulting", "Electrical Work", "Smart Home Setup", 
          "Pond Cleaning", "Window Replacement", "Gutter Repair", "Home Safety Inspection", 
          "Solar Panel Installation", "Electrical Panel Upgrade", "Septic System Repair", 
          "Water Filtration Installation", "Driveway Sealing", "Fence Installation", 
          "Concrete Work", "Tiling", "Carpet Installation", "Floor Polishing", 
          "Cabinet Installation", "Countertop Installation", "Interior Design Consulting", 
          "Home Staging", "Personal Shopping", "Car Detailing", "Window Tinting", 
          "Boat Cleaning", "RV Cleaning", "Deck Repair", "Porch Repair", 
          "Masonry Work", "Chimney Sweep", "Waterproofing", "Basement Finishing", 
          "Foundation Repair", "Storm Damage Repair", "Fire Damage Restoration", 
          "Flood Damage Restoration", "Mold Remediation", "Insulation Installation", 
          "Duct Repair", "Tree Removal", "Yard Cleanup", "Mulching", 
          "Landscape Design", "Artificial Turf Installation", "Irrigation System Repair", 
          "Sprinkler Installation", "Water Feature Installation", "Fence Staining", 
          "Pool Maintenance", "Spa Maintenance", "Hot Tub Repair", "Gazebo Installation", 
          "Pergola Installation", "Deck Building", "Screen Repair", "Storm Door Installation", 
          "Weather Stripping Installation", "Window Sealing", "Mailbox Installation", 
          "Lighting Design", "Chandelier Installation", "Smart Thermostat Installation", 
          "Backup Generator Installation", "Attic Fan Installation", "Security Camera Setup", 
          "Baby Proofing", "Household Management", "Elderly Companion Care", 
          "Concierge Services", "Event Planning", "Wedding Planning", "Party Setup", 
          "Holiday Decoration", "Balloon Art", "Clown Services", "Magician Services", 
          "Catering", "Food Truck Catering", "Bartending", "Waitstaff Services", 
          "Chef Services", "Personal Trainer", "Yoga Instructor", "Massage Therapy", 
          "Reiki Healing", "Nutrition Consulting", "Life Coaching", "Therapy Services", 
          "Financial Planning", "Tax Preparation", "Bookkeeping", "Virtual Assistant", 
          "Tutoring", "Test Prep", "Language Lessons", "Music Lessons", 
          "Instrument Repair", "Recording Studio Setup", "Music Production", "Photography", 
          "Videography", "DJ Services", "Photo Booth Rental", "Graphic Design", 
          "Web Design", "App Development", "SEO Consulting", "Social Media Management", 
          "Branding", "Content Creation", "Marketing Strategy", "Advertising Services", 
          "Public Relations", "Event Coordination", "Business Consulting", 
          "Leadership Coaching", "Sales Training", "Customer Service Training", 
          "Product Design", "Prototype Development", "Patent Consulting", 
          "E-commerce Setup", "Inventory Management", "Shipping Services", 
          "Drop Shipping Consulting", "Custom Packaging", "Gift Wrapping", 
          "Courier Services", "Document Delivery", "Notary Services", "Legal Consulting", 
          "Real Estate Consulting", "Property Management", "Vacation Rental Management", 
          "Estate Planning", "Title Services", "Auctioneering", "Fundraising Consulting", 
          "Grant Writing", "Proposal Writing", "Market Research", "Data Analysis", 
          "Survey Design", "Focus Group Facilitation", "Crowdsourcing Consulting", 
          "HR Consulting", "Payroll Services", "Recruitment", "Job Placement", 
          "Career Coaching", "Resume Writing", "Interview Coaching", "Job Search Assistance", 
          "Personal Stylist", "Wardrobe Consulting", "Closet Revamp", "Fashion Design", 
          "Clothing Alterations", "Tailoring", "Shoe Repair", "Jewelry Design", 
          "Makeup Artist", "Hair Stylist", "Nail Technician", "Barbering", 
          "Tattoo Artist", "Piercing Services", "Spa Services", "Eyebrow Threading", 
          "Lash Extensions", "Skincare Consulting", "Weight Loss Consulting", 
          "Health Coaching", "Chiropractic Care", "Acupuncture", "Aromatherapy", 
          "Hypnotherapy", "Feng Shui Consulting", "Tarot Reading", "Astrology Consulting", 
          "Pet Training", "Pet Boarding", "Dog Grooming", "Aquarium Maintenance", 
          "Exotic Pet Care", "Horse Grooming", "Stable Cleaning", "Farm Sitting", 
          "Poultry Care", "Beekeeping", "Plant Nursery Services", "Composting", 
          "Sustainable Gardening", "Green Roof Installation", "Aquaponics Setup", 
          "Hydroponics Setup", "Organic Farming", "Permaculture Design", "Wildlife Removal", 
          "Bird Control", "Bat Removal", "Squirrel Removal", "Snake Removal"    
      ]
      res.json(skillSet);
}

async function otpGenerator(req,res){
  const otp = Math.floor(100000 + Math.random() * 900000);
  res.otp=otp
}

module.exports={getSkillSet,otpGenerator};